// File generated by FlutterFire CLI.
// This file should be version controlled.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClG1zFNb6sflC0yKO-Mmbawqq6ReqazpI',
    appId: '1:344064372155:web:d048bd8775c66ce435a89e',
    messagingSenderId: '344064372155',
    projectId: 'gourmetai-c432b',
    authDomain: 'gourmetai-c432b.firebaseapp.com',
    storageBucket: 'gourmetai-c432b.firebasestorage.app',
    measurementId: 'G-FF9QL56EDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCmVcmaR9C-FRJz_B2MlfcgNG-WemFQQU',
    appId: '1:344064372155:android:6b1925804b3dc59035a89e',
    messagingSenderId: '344064372155',
    projectId: 'gourmetai-c432b',
    storageBucket: 'gourmetai-c432b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvz7xL7VRfbTrvWaabQuKpWLjIq-m04nE',
    appId: '1:344064372155:ios:2752f2b789c330fe35a89e',
    messagingSenderId: '344064372155',
    projectId: 'gourmetai-c432b',
    authDomain: 'gourmetai-c432b.firebaseapp.com',
    storageBucket: 'gourmetai-c432b.firebasestorage.app',
    iosBundleId: 'com.foodgenius.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClG1zFNb6sflC0yKO-Mmbawqq6ReqazpI',
    appId: '1:34406437215:ios:XXXXX',
    messagingSenderId: '34406437215',
    projectId: 'gourmetai-c432b',
    authDomain: 'gourmetai-c432b.firebaseapp.com',
    storageBucket: 'gourmetai-c432b.firebasestorage.app',
    iosBundleId: 'com.example.gourmetai',
  );
}
